name: validator

on:
  pull_request:
    branches:
      - main
    paths:
      - 'data/*'
      - 'images/*'

jobs:
  check-modified-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: data 폴더와 images 폴더에만 데이터가 올라왔는지 확인합니다.
        run: |
          MODIFIED_FILES=$(git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.sha }})
          ALLOWED_PATTERN="^(data|images)/[^/]*$"
          for FILE in $MODIFIED_FILES; do
            if ! [[ "$FILE" =~ $ALLOWED_PATTERN ]]; then
              echo "허락 되지 않은 데이터 수정이 있습니다.: $FILE"
              exit 1
            fi
          done
          echo "모든 데이터가 정해진 위치에 업로드 되었습니다."

  verify-json-validation:
    needs: check-modified-paths
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JSON 검사 중...
        id: validate
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schema.json
          jsons: data/*.json

      - name: JSON 검사 실패
        if: steps.validate.outcome == 'failure'
        run: |
          echo "json 파일이 이상합니다. 다시 시도해 주세요."
          exit 1

      - name: 데이터 업로드 성공
        if: success()
        run: |
          echo "모든 데이터가 정상적으로 업로드 되었습니다."
